bump the sample operatior to 0.49.2
FoundationDB/fdb-kubernetes-operator pull request #1049
Opened 2022-01-22 14:45 UTC by sevki

# Description
0.49.0 doesn't exist so bumping the version to 0.49.2
https://hub.docker.com/r/foundationdb/fdb-kubernetes-operator/tags?page=1&name=49

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Testing

`docker pull foundationdb/fdb-kubernetes-operator:v0.49.2`

# Documentation

*Did you update relevant documentation within this repository?*
no updates required
*If this change is adding new functionality, do we need to describe it in our user manual?*
its not
*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*
it's not
*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*
it's not
# Follow-up

*Are there any follow-up issues that we should pursue in the future?*
it'd be nice to make sure image tags in sample deployments are valid

2022-01-23 06:45 UTC, johscheuer requested changes
Thanks for taking the time and fixing it could you also adjust the following files:

- config/samples/deployment/manager.yaml
- helm/fdb-operator/values.yaml

Then we are good to go.

2022-01-23 06:45 UTC, johscheuer commented on config/samples/deployment.yaml
> +        image: foundationdb/fdb-kubernetes-operator:v0.49.2
```suggestion
        image: foundationdb/fdb-kubernetes-operator:v0.50.0
```

We already released the `v0.50.0` version so we want to update to the latest version here. I guess we missed that step in the release process.

2022-01-23 06:57 UTC, johscheuer reviewed
I just noticed that our release process was not finished and the new version was already available and correctly set in the tag but those changes were never added to the main. branch. I fixed that: https://github.com/FoundationDB/fdb-kubernetes-operator/commit/8ea50b7b6e2d33e3dbbfe73cec175fc9263b1fd5 sorry for the inconvenience.

2022-01-23 07:35 UTC, sevki commented
@johscheuer no need to apologize, I'm glad I can help fix a tiny bug :) have a great weekend!

2022-02-04 18:20 UTC, johscheuer commented
With the latest release those changes are obsolete. Sorry for the delay and thanks for the PR.

2022-02-04 18:20 UTC, closed without merging

2022-02-04 18:23 UTC, sevki commented
Ha. @johscheuer no worries. on an unrelated note, why are the build logs private?

2022-02-05 21:38 UTC, johscheuer commented
Good question, the build logs should be open for everyone under the provided link. I just checked a few other PRs and there the link works fine. I keep an eye on thath.