Drop support for 6.1
FoundationDB/fdb-kubernetes-operator pull request #1056
Opened 2022-02-02 11:42 UTC by johscheuer

# Description

Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/743

## Type of change

*Please select one of the options below.*

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Discussion

I added the new compatibility to our docs. We might want to consider to remove some older `6.2` versions to reduce our if branching.

# Testing

local.

# Documentation

Added.

# Follow-up

-

2022-02-02 11:43 UTC, johscheuer commented on api/v1beta1/foundationdb_version.go
> +	MinimumVersion:                       FdbVersion{Major: 6, Minor: 2, Patch: 0},
I think a good minimum version would be `6.2.20` that would allow us to remove nearly all of the version specific behaviour.

2022-02-02 11:43 UTC, johscheuer commented on docs/compatibility.md
> +| 0.52.0+          | -                   | v1beta1                   | 6.2.0+                | 1.19.0+                       |
I decided to increase the Kubernetes version to `1.19` since our tests are not testing against `1.15` so we might not support that version.

2022-02-02 16:35 UTC, johscheuer commented on api/v1beta1/foundationdb_version.go
> +	MinimumVersion:                       FdbVersion{Major: 6, Minor: 2, Patch: 0},
The minimum version should be 6.3.22, try to find the documentation in the forum and document it.

2022-02-08 23:33 UTC, brownleej requested changes

2022-02-08 23:33 UTC, brownleej commented on docs/compatibility.md
> -| 0.x               | 0.51.0              | v1beta1                   | 6.1.12+                 | 1.15.0+                       |
I think that we should keep this table with one entry per major version of the operator, in order to keep things simple for users of the operator. That means that we need to commit to making the changes in this PR part of a major release and retain compatibility with older versions of FDB in the 0.x family.

2022-02-08 23:33 UTC, brownleej commented on internal/monitor_conf_test.go
> -				cluster.Spec.Version = fdbtypes.Versions.WithBinariesFromMainContainer.String()
Do we still need a special test case for this if it is the only supported behavior?

2022-02-08 23:33 UTC, brownleej commented on internal/pod_models_test.go
> +				cluster.Spec.Version = fdbtypes.Versions.Default.String()
Do we still need a special test case for this if it is the only supported behavior?

2022-02-08 23:33 UTC, brownleej commented on internal/pod_models_test.go
> +				backup.Spec.Version = fdbtypes.Versions.Default.String()
Another test case we may not need.

2022-02-11 10:19 UTC, merged