Increase process group prefix length
FoundationDB/fdb-kubernetes-operator pull request #1060
Opened 2022-02-11 12:11 UTC by johscheuer

# Description

Increase the length of the prefix.

## Type of change

*Please select one of the options below.*

- Bug fix (non-breaking change which fixes an issue)

# Discussion

-

# Testing

local

# Documentation

-

# Follow-up

-

2022-02-11 15:32 UTC, johscheuer commented on api/v1beta1/foundationdbcluster_types.go
> +	// +kubebuilder:validation:MaxLength=64
TODO: Remove the link above. The prefix will be used a s value not as key.

2022-02-11 16:37 UTC, johscheuer commented on api/v1beta1/foundationdbcluster_types.go
> +	// +kubebuilder:validation:MaxLength=64
Another note we should not exceed 63 (this is the maximum for a label value). I would guess that `cluster-controller` (19 chars) is currently the longest role so we should be fine to have 63-20= 43 as `MaxLength`

2022-02-22 00:38 UTC, brownleej requested changes
Requesting changes to address the previous discussion on the length limitation.

2022-03-09 06:19 UTC, johscheuer commented on api/v1beta1/foundationdbcluster_types.go
> +	// +kubebuilder:validation:MaxLength=43
I think that makes sense but not as part of this PR. I can open an issue and we can look at this in another PR.

2022-03-09 06:26 UTC, johscheuer commented on api/v1beta1/foundationdbcluster_types.go
> +	// +kubebuilder:validation:MaxLength=43
Opened: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1096

2022-03-09 18:31 UTC, brownleej approved these changes
LGTM. I'm guessing that the deployment YAML change is going to get wiped out by a rebase. Can you rebase to make sure everything is consistent?

2022-03-10 05:55 UTC, johscheuer commented
The files checks have passed so I'm going ahead and merge this PR.

2022-03-10 05:55 UTC, merged