Add test process count
FoundationDB/fdb-kubernetes-operator pull request #1362
Opened 2022-09-26 12:50 UTC by iyuroch

# Description

This PR adds "test" processCount.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Discussion

This changes are based on discussion under 
https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1346

## Testing

Unit test

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

## Documentation

Yes, added description in fdb cluster page.

## Follow-up

Add deprecation for tester
Does not have anything

2022-09-26 16:26 UTC, johscheuer approved these changes
LGTM 👍 Have you run a local test with those changes?

2022-09-26 16:33 UTC, iyuroch commented
@johscheuer I'll fix them, have to pull amd hardware.

2022-09-26 17:10 UTC, johscheuer commented
> @johscheuer I'll fix them, have to pull amd hardware.

Most of the command can also be run with docker e.g. https://github.com/FoundationDB/fdb-kubernetes-operator#local-development-with-arm64 (or your favourite container runtime). Just a heads up if you run things inside docker everything will be quite slow and a dedicated VM might be faster.

2022-09-26 17:11 UTC, johscheuer requested changes
Waiting until all tests are pass. Otherwise the change LGTM.

2022-09-28 07:19 UTC, iyuroch commented
@johscheuer I don't see operator_velocity_test tests located in this repository. Can you please point me where to look to find simulated scenario?

2022-09-28 07:40 UTC, johscheuer approved these changes
The test failure is unrelated to those changes (see: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1361).

2022-09-28 07:41 UTC, johscheuer commented
> @johscheuer I don't see operator_velocity_test tests located in this repository. Can you please point me where to look to find simulated scenario?

Sadly they are currently not open-source (we are working on that). Thanks for creating the PR!

2022-11-02 20:52 UTC, brownleej approved these changes
👍

2022-11-02 20:52 UTC, merged