Initial doc for replacement buckets
FoundationDB/fdb-kubernetes-operator pull request #1368
Opened 2022-10-03 13:01 UTC by johscheuer

# Description

Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1316

## Type of change

- New feature (non-breaking change which adds functionality)

## Discussion

-

## Testing

-

## Documentation

-

## Follow-up

I will write another design doc for allowing replacements on a fault domain basis.

2022-10-03 13:01 UTC, johscheuer commented
CC @saintstack @RenxuanW please provide feedback on this idea.

2022-10-13 17:37 UTC, brownleej requested changes

2022-10-13 18:19 UTC, xumengpanda commented on docs/design/replacement_buckets.md
> +Allow a human operator to define replacement buckets which allow to set limits on a per process class base.
does operator have a safeguard to prevent human error (e.g., set the limits too high?)

2023-10-10 14:47 UTC, johscheuer commented on docs/design/replacement_buckets.md
> +	// If set the ReplacementBucket will be used. Defaults to false.
Updated.

2023-10-12 08:21 UTC, AnnigeriShambu approved these changes

2023-10-12 17:27 UTC, brownleej approved these changes
👍

2023-10-13 05:20 UTC, merged