Creating a new type ProcessGroupID
FoundationDB/fdb-kubernetes-operator pull request #1498
Opened 2023-02-09 16:32 UTC by 09harsh

# Description

*Please include a summary of the change and which issue is addressed. If this change resolves an issue, please include the issue number in the description.*

Created a new type `ProcessGroupID` to represent process group ID instead of using string

## Type of change

*Please select one of the options below.*

- New feature (non-breaking change which adds functionality)

## Discussion

*Are there any design details that you would like to discuss further?*
No

## Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Manual testing?*

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*
Not needed, ran the existing test cases and checked fit lint errors
## Documentation

*Did you update relevant documentation within this repository?*

*If this change is adding new functionality, do we need to describe it in our user manual?*

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*

## Follow-up

*Are there any follow-up issues that we should pursue in the future?*

*Does this introduce new defaults that we should re-evaluate in the future?*

2023-02-09 19:17 UTC, xumengpanda commented
In the description section, could you please explain why a new type should be added? 
is it to eventually replace the string type, which is subjected to typo without notice?

2023-02-10 06:13 UTC, johscheuer requested changes
Is there a reason you changed all occurrences of `processes` with `podNames` in all files?

2023-02-10 06:13 UTC, johscheuer commented on api/v1beta2/foundationdbcluster_types.go
> +// +kubebuilder:validation:MaxLength=1024
I don't think length of 1024 is reasonable here, a realistic value is `63` based on https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set.

2023-02-10 06:13 UTC, johscheuer commented on docs/changelog/CHANGELOG.md
> +*	Add an option to use service IPs for the public IPs for FDB podNames.
Why are we changing the old changelogs?

2023-02-10 06:13 UTC, johscheuer commented on docs/design/bin_pack_fault_domains.md
> +The label selector will contain the process class and the cluster name, to ensure podNames with the same class are distributed across different fault domains is possible.
Why was that changed?

2023-02-10 06:13 UTC, johscheuer commented on docs/design/bin_pack_fault_domains.md
> +  The idea is to have a way to group some podNames of a FoundationDB cluster together with the same zone ID, this zone ID will be a logical value like "zone-1".
Why was that changed?

2023-02-10 06:13 UTC, johscheuer commented on docs/design/bin_pack_fault_domains.md
> +We also don't guarantee that we use exactly the number of `DesiredFaultDomains` e.g. when we spawn fewer podNames than `DesiredFaultDomains`.
Why was that changed?

2023-02-10 06:13 UTC, johscheuer commented on docs/design/implemented/automatic_replacements.md
> +Replacing failed podNames can be a major source of operational toil when running FoundationDB. This is especially true when using local disks, which expose the service to a wide variety of failure mo
Why was that changed?

2023-02-10 06:14 UTC, johscheuer reviewed
@xumengpanda here is some more information: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1476

2023-02-10 10:56 UTC, 09harsh commented on CONTRIBUTING.md
> +At project launch, FoundationDB has a light governance structure. The intention is for the community to evolve quickly and adopt additional podNames as participation grows. Stay tuned, and stay engag
These were changed automatically, I just ran 
`make all` 
which did all the changes 🤔

2023-02-10 11:09 UTC, johscheuer commented on CONTRIBUTING.md
> +At project launch, FoundationDB has a light governance structure. The intention is for the community to evolve quickly and adopt additional podNames as participation grows. Stay tuned, and stay engag
That would be more than surprising if `make all` was the cause of that. Especially since this fine is not generated.

2023-02-14 10:42 UTC, johscheuer approved these changes
Changes LGTM 👍

2023-02-21 14:49 UTC, johscheuer reviewed
Can you make sure that this PR includes the changes from main? That should make the tests pass.

2023-02-22 11:30 UTC, merged