Add kube builder validation checks for a couple of entries.
FoundationDB/fdb-kubernetes-operator pull request #1544
Opened 2023-03-17 21:09 UTC by bnamasivayam

# Description

Add kubebuilder validations for a couple of entries

## Type of change

*Please select one of the options below.*

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation
- Other

## Discussion

*Are there any design details that you would like to discuss further?*

## Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Used kubectl --dry-run to apply the new crd's

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

## Documentation

*Did you update relevant documentation within this repository?*

*If this change is adding new functionality, do we need to describe it in our user manual?*

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*

## Follow-up

*Are there any follow-up issues that we should pursue in the future?*

*Does this introduce new defaults that we should re-evaluate in the future?*

2023-03-17 21:17 UTC, ammolitor approved these changes

2023-03-18 07:37 UTC, johscheuer requested changes

2023-03-18 07:37 UTC, johscheuer commented on api/v1beta2/foundationdbcluster_types.go
> +	// +kubebuilder:validation:MaxItems=10000
```suggestion
	// +kubebuilder:validation:MaxItems=200
```

I would prefer to have a more reasonable value here. I would like to see the FDB cluster that has 10000 processes per zone :)

2023-03-21 00:10 UTC, ammolitor approved these changes

2023-03-21 00:13 UTC, merged