Initial commit for supporting multiple Log processes per disk
FoundationDB/fdb-kubernetes-operator pull request #1686
Opened 2023-06-19 14:06 UTC by AnnigeriShambu

# Description

*Please include a summary of the change and which issue is addressed. If this change resolves an issue, please include the issue number in the description.*

## Type of change

*Please select one of the options below.*

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation
- Other

## Discussion

*Are there any design details that you would like to discuss further?*

## Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Manual testing?*

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

## Documentation

*Did you update relevant documentation within this repository?*

*If this change is adding new functionality, do we need to describe it in our user manual?*

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*

## Follow-up

*Are there any follow-up issues that we should pursue in the future?*

*Does this introduce new defaults that we should re-evaluate in the future?*

2023-06-28 13:02 UTC, johscheuer commented on api/v1beta2/foundationdbcluster_types.go
> +	TLogServersPerDisk []int `json:"tLogServersPerDisk,omitempty"`
```suggestion
	LogServersPerDisk []int `json:"logServersPerDisk,omitempty"`
```

2023-06-28 13:08 UTC, johscheuer commented on controllers/bounce_processes.go
> +	if cluster.Spec.TLogProcessesPerPod > 1 {
I'm okay with copy and paste here but in general it would be better to have a method here to reuse the same logic.

2023-06-28 13:10 UTC, johscheuer commented on e2e/fixtures/fdb_cluster.go
> +// GetStorageServerPerPod returns the current expected storage server per pod.
```suggestion
// GetTLogServersPerPod returns the current expected log server per Pod.
```

2023-06-28 13:31 UTC, johscheuer commented on internal/configmap_helper.go
> +				for _, serversPerPod := range logServersPerDisk {
Instead of copying the whole block, can we build a method to handle this?

2023-06-30 08:02 UTC, johscheuer requested changes

2023-06-30 08:02 UTC, johscheuer commented on internal/pod_models.go
> +func GetServersPerPodForPod(pod *corev1.Pod, pClass fdbv1beta2.ProcessClass) (int, error) {
The process class can be fetched from the Pod metadata: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/pkg/podmanager/fdb_process_group.go#L57

2023-06-30 08:24 UTC, johscheuer requested changes

2023-06-30 08:24 UTC, johscheuer commented on internal/pod_models.go
> +			sidecarContainer.Env = append(sidecarContainer.Env, corev1.EnvVar{Name: "LOG_SERVERS_PER_POD", Value: fmt.Sprintf("%d", cluster.GetStorageServersPerPod())})
```suggestion
		if processClass == fdbv1beta2.ProcessClassLog && cluster.GetLogServersPerPod() > 1 {
			sidecarContainer.Env = append(sidecarContainer.Env, corev1.EnvVar{Name: "LOG_SERVERS_PER_POD", Value: fmt.Sprintf("%d", cluster.GetLogServersPerPod())})
```

Please make sure that the unit tests are passing. This should make sure that we catch such issues.

2023-07-04 09:29 UTC, johscheuer commented on controllers/bounce_processes.go
> +		expectedProcesses += counts.Log * (cluster.Spec.LogServersPerPod - 1)
We have to make sure that we also check the transaction servers too.

2023-07-04 09:29 UTC, johscheuer commented on controllers/cluster_controller_test.go
> +			It("should generate the storage conf with two processes", func() {
This should ne `log conf` and not `storage conf`.

2023-07-04 09:29 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +	FWhen("setting 2 logs per disk", func() {
The focus can be removed.

2023-07-04 09:29 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			log.Printf("set storage server per Pod to %d", serverPerPod)
That should be log servers, same for the log line below.

2023-07-05 22:08 UTC, AnnigeriShambu commented
Test cases are passing. I will try again running PR builder now
```
Ran 25 of 34 Specs in 4451.201 seconds
SUCCESS! -- 25 Passed | 0 Failed | 8 Pending | 1 Skipped
--- PASS: TestOperatorCreationVelocity (4451.21s)
PASS
ok  	github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator	4451.696s
```

2023-07-05 22:09 UTC, AnnigeriShambu commented
test this please

2023-07-06 12:07 UTC, johscheuer requested changes

2023-07-06 12:07 UTC, johscheuer commented on e2e/fixtures/factory.go
> +	config.SetDefaults(factory)
Any reason for those changes?

2023-07-06 12:07 UTC, johscheuer commented on e2e/fixtures/fdb_cluster.go
> +func (fdbCluster *FdbCluster) SetLogServersPerPod(serverPerPod int) error {
Why do we need two methods here?

2023-07-06 12:07 UTC, johscheuer commented on e2e/fixtures/fdb_cluster.go
> +func (fdbCluster *FdbCluster) SetTransactionServerPerPod(serverPerPod int, processCount int) error {
Same here, why do we need two methods?

2023-07-06 12:07 UTC, johscheuer commented on e2e/fixtures/fdb_cluster.go
> +		"Upgrading cluster from version %s to version %s and logServerPerPod %d clusterSpec %d",
```suggestion
		"Upgrading cluster from version %s to version %s",
```

This was ok during debugging, but we don't want to have these values printed out the whole time.

2023-07-06 12:07 UTC, johscheuer commented on e2e/fixtures/fdb_cluster.go
> +		fdbCluster.cluster.Spec.LogServersPerPod,
```suggestion
```

See comment above.

2023-07-06 12:07 UTC, johscheuer commented on e2e/fixtures/status.go
> +func (fdbCluster *FdbCluster) GetProcessCountByProcessClass(pCloass fdbv1beta2.ProcessClass) int {
```suggestion
func (fdbCluster *FdbCluster) GetProcessCountByProcessClass(pClass fdbv1beta2.ProcessClass) int {
```

2023-07-06 12:07 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			}).Should(BeNumerically("==", 10))
Can we change this to make use of `validateProcessesCount`?

2023-07-06 12:07 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			}).Should(BeNumerically("==", 10))
Can we change this to make use of `validateProcessesCount`? This would reduce copy and paste code.

2023-07-06 12:07 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			}).Should(BeNumerically("==", 10))
Can we make use of `validateProcessesCount`?

2023-07-06 12:07 UTC, johscheuer commented on e2e/test_operator_upgrades/operator_upgrades_test.go
> +					if processGroup.ProcessClass == fdbv1beta2.ProcessClassLog {
Why are we skipping log processes here?

2023-07-06 12:07 UTC, johscheuer commented on e2e/test_operator_upgrades/operator_upgrades_test.go
> +			expectedProcessCounts := (processCounts.Total()-processCounts.Log)*2 + 5
Why are we removing the log processes here? The intention of this check is to make sure we are replacing the transaction system pods only once.

2023-07-07 13:08 UTC, johscheuer requested changes

2023-07-07 13:08 UTC, johscheuer commented on e2e/fixtures/fdb_cluster.go
> +// SetTransactionServerPerPod set the SetTransactionServerPerPod field in the cluster spec.
```suggestion
// SetTransactionServerPerPod set the LogServersPerPod field in the cluster spec and changes log Pods to transaction Pods..
```

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			validateProcessesCount(fdbCluster, fdbv1beta2.ProcessRoleStorage, expectedPodCnt, 10)
Any reason to hardcode `10` here?

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			validateProcessesCount(fdbCluster, fdbv1beta2.ProcessRoleLog, expectedPodCnt, 10)
Any reason to hardcode `10` here?

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			validateProcessesCount(fdbCluster, fdbv1beta2.ProcessRole(fdbv1beta2.ProcessClassTransaction), expectedPodCnt, 10)
Any reason to hardcode `10` here?

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +	When("setting 2 logs per disk to use Transaction process", func() {
```suggestion
	When("setting 2 logs per disk with transaction processes", func() {
```

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +		It("should update the log servers to the expected amount", func() {
```suggestion
		It("should update the log servers to the expected amount and should create transaction Pods", func() {
```

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			Expect(fdbCluster.SetLogServersPerPod(serverPerPod, true)).ShouldNot(HaveOccurred())
Why do we have to call this again? `fdbCluster.SetTransactionServerPerPod` should set this value already?

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			Expect(fdbCluster.SetTransactionServerPerPod(serverPerPod, 5, true)).ShouldNot(HaveOccurred())
Why are we hardcoding `5` here?

2023-07-07 13:08 UTC, johscheuer commented on e2e/test_operator/operator_test.go
> +			Expect(fdbCluster.SetLogServersPerPod(initialLogServerPerPod, true)).ShouldNot(HaveOccurred())
Where are we resetting the transaction Pods to 0 again and make use of log Pods?

2023-07-11 06:44 UTC, johscheuer requested changes

2023-07-11 06:44 UTC, johscheuer commented on e2e/test_operator_upgrades/operator_upgrades_test.go
> +			Expect(len(transactionSystemProcessGroups)).To(BeNumerically("<=", processCounts.Transaction))
```suggestion
			expectedProcessCounts := (processCounts.Total()-processCounts.Storage)*2 + 5
			Expect(len(transactionSystemProcessGroups)).To(BeNumerically("<=", expectedProcessCounts))
```

We have to get all process counts without the storage counts, multiply it by 2 to get the number of expected process counts.

2023-07-11 12:59 UTC, johscheuer approved these changes

2023-07-11 12:59 UTC, merged