Split deployment.yaml config sample RBAC roles
FoundationDB/fdb-kubernetes-operator pull request #1734
Opened 2023-07-11 13:46 UTC by manfontan

# Description

Because https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1727 the operator does not work if the deployment doesn't have RBAC access to listing nodes. This PR mitigates this issue for users relying on deployment config sample to build their cluster manifests.

The deployment config smaple uses a RoleBinding pointing to a ClusterRole. This configuration will not allow to list nodes.

In this PR we split the ClusterRole in two ClusterRoles one to access namespace scoped resources and another to access cluster-wide (nodes) resources. Using a RoleBinding for the first and a ClusterRoleBinding for the former.

## Type of change

*Please select one of the options below.*

- Bug fix (non-breaking change which fixes an issue)

## Discussion

*Are there any design details that you would like to discuss further?*

## Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Manual testing?*

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

## Documentation

*Did you update relevant documentation within this repository?*

*If this change is adding new functionality, do we need to describe it in our user manual?*

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*

## Follow-up

*Are there any follow-up issues that we should pursue in the future?*

*Does this introduce new defaults that we should re-evaluate in the future?*

2023-07-11 14:43 UTC, johscheuer requested changes

2023-07-11 18:41 UTC, manfontan commented on config/samples/deployment.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
🤔 ok looks like roles.yaml is also generated using https://book.kubebuilder.io/reference/markers/rbac.html
But it does not support adding multiple ClusterRoles.
https://github.com/FoundationDB/fdb-kubernetes-operator/blob/d21d0f37f99c83ee228bd08a7eaaa28becf801a1/controllers/cluster_controller.go#L81
Any suggestions?

2023-07-11 18:57 UTC, manfontan commented on config/samples/deployment.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
I can add a cluster_role.yaml and remove the `kubebuilder:rbac` entry for `nodes`. 
Not super elegant but it does the job.

2023-07-13 09:54 UTC, johscheuer approved these changes
LGTM 👍

2023-07-13 09:54 UTC, johscheuer commented on config/rbac/cluster_role.yaml
> +  - watch
Can we add a newline here?

2023-07-13 09:54 UTC, johscheuer commented on config/rbac/kustomization.yaml
> +- cluster_role.yaml
Can we add a newline here?

2023-07-13 09:54 UTC, johscheuer commented on config/samples/deployment.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
This seems like a reasonable approach, given the limitations from Kubebuilder.

2023-07-25 12:07 UTC, johscheuer approved these changes
Sorry for the delay, changes LGTM 👍

2023-07-25 12:08 UTC, merged