Add workaround for missing CA (see: #252)
FoundationDB/fdb-kubernetes-operator pull request #318
Opened 2020-09-03 16:28 UTC by johscheuer

Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/252

This PR adds a workaround for the issue with the missing CA. During the build time the CA will be added and afterwards removed so the resulting image won't have the CA. This is an intermediate solution until the FDB website get another certificate.

2020-09-10 17:44 UTC, brownleej requested changes

2020-09-10 17:44 UTC, brownleej commented on Dockerfile
> +    curl -sLo /usr/local/share/ca-certificates/GeoTrust_Global_CA.crt https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem && \
Rather than downloading the CA at build-time, can we add it to our repo and copy it into the build? I think pinning it that way will be more secure.

2020-09-11 15:26 UTC, johscheuer commented on foundationdb-kubernetes-sidecar/files/GeoTrust_Global_CA.pem
> +-----BEGIN CERTIFICATE-----
I put the file this directory so we only need to store it once (and Docker only allows to copy files from subdirectories or the same directory).

2020-09-13 19:21 UTC, brownleej approved these changes
👍

2020-09-13 19:26 UTC, merged