Initial support for ProcessGroups
FoundationDB/fdb-kubernetes-operator pull request #422
Opened 2020-12-09 16:49 UTC by johscheuer

Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/410

This PR adds the `ProcessGroups` proposed in https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/design/process_group_status.md. Currently the status is not used by the reconciler and will only be filled in in the `update_status` reconciler. The next step is to actually use the fields instead of the deprecated fields.

2020-12-09 17:40 UTC, johscheuer commented
The resulting status for my test cluster:

```yaml   
 processGroups:
    - addresses:
      - 10.1.1.193
      grocessGroupID: cluster_controller-1
      processClass: cluster_controller
    - addresses:
      - 10.1.1.195
      grocessGroupID: log-1
      processClass: log
    - addresses:
      - 10.1.1.198
      grocessGroupID: log-2
      processClass: log
    - addresses:
      - 10.1.1.196
      grocessGroupID: log-3
      processClass: log
    - addresses:
      - 10.1.1.194
      grocessGroupID: log-4
      processClass: log
    - addresses:
      - 10.1.1.192
      grocessGroupID: storage-1
      processClass: storage
    - addresses:
      - 10.1.1.191
      grocessGroupID: storage-2
      processClass: storage
    - addresses:
      - 10.1.1.197
      grocessGroupID: storage-3
      processClass: storage
```

2020-12-10 20:39 UTC, brownleej requested changes
Found a typo. Otherwise LGTM

2020-12-10 20:39 UTC, brownleej commented on api/v1beta1/foundationdbcluster_types.go
> +	ProcessGroupID string `json:"grocessGroupID,omitempty"`
```suggestion
	ProcessGroupID string `json:"processGroupID,omitempty"`
```

2020-12-11 07:02 UTC, johscheuer commented on api/v1beta1/foundationdbcluster_types.go
> +	ProcessGroupID string `json:"grocessGroupID,omitempty"`
🤦 Thanks!

2020-12-11 07:40 UTC, johscheuer commented
Rebased for the kustomize fix.

2021-01-13 16:51 UTC, brownleej approved these changes
👍

2021-01-14 16:44 UTC, johscheuer commented on controllers/update_status.go
> +	if !equality.Semantic.DeepEqual(cluster.Status, *originalStatus) {
@brownleej I changed this to be robust against different pointers but the same content `reflect.DeepEqual` will check if the pointers are the same and `equality.Semantic.DeepEqual` will check if the content is the same which makes more sense in our case.

2021-01-15 19:14 UTC, brownleej commented
This looks good. Can you take a look at the ProcessGroupID JSON tag again, and clean up the merge conflicts?

2021-01-15 19:14 UTC, brownleej approved these changes
This looks good. Can you take a look at the ProcessGroupID JSON tag again, and clean up the merge conflicts?

2021-01-19 17:21 UTC, brownleej approved these changes
👍

2021-01-20 18:58 UTC, merged