Allow override of deployment replicas value
FoundationDB/fdb-kubernetes-operator pull request #430
Opened 2020-12-10 09:48 UTC by funkypenguin

This PR allows the helm-chart deployer the ability to customize the amount of replicas in the deployment. A potential future enhancement in this area would be to add a PodDisruptionBudget, as well as affinity settings, to accommodate availability requirements on an HA cluster.

2020-12-10 09:59 UTC, johscheuer requested changes

2020-12-10 09:59 UTC, johscheuer commented on helm/fdb-operator/values.yaml
> +  replicas: 1
NIT: missing newline

2020-12-10 10:00 UTC, johscheuer commented
We can add a `PodDisruptionBudget` optionally but the availability of the operator doesn't directly effect the availability of the database itself.

2020-12-10 20:06 UTC, funkypenguin commented on helm/fdb-operator/values.yaml
> +  replicas: 1
Fixed :)

2020-12-10 20:07 UTC, funkypenguin commented
> We can add a `PodDisruptionBudget` optionally but the availability of the operator doesn't directly effect the availability of the database itself.

Agreed, it's a nice-to-have in future, and I felt that adding it to this changeset was unnecessary :)

2020-12-11 07:36 UTC, johscheuer approved these changes
👍

2020-12-11 07:37 UTC, johscheuer commented
Once the conflict is solved I merge the PR. Thanks!

2020-12-11 07:45 UTC, funkypenguin commented
Conflict resolved ;)

2020-12-11 08:48 UTC, merged

2020-12-11 08:48 UTC, johscheuer commented
Thanks!