Enable using custom image tags
FoundationDB/fdb-kubernetes-operator pull request #671
Opened 2021-05-07 19:27 UTC by Daniel-B-Smith

This is related to: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/610

The previous version regex would only match image tags that were exclusively a version tag (e.g. "7.0.0" but not "foo-7.0.0"). When building custom images in development, we want to be able to add some additional context to avoid conflicts / confusing with official releases. This PR allows for the version to be extracted from image tags like "foo-7.0.0".

2021-05-07 19:53 UTC, johscheuer requested changes
You also have to adjust the regex here: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/api/v1beta1/foundationdbcluster_types.go#L73 (and run `make clean all`) otherwise the CRD will prevent setting the version.

2021-05-07 21:39 UTC, Daniel-B-Smith commented
I _think_ enough of the make command succeeded to get the changes needed.

2021-05-08 10:18 UTC, johscheuer commented on config/samples/deployment.yaml
> -apiVersion: v1
It seems that one step has failed since the deployment is removed. Let's have a look at this on Monday.

2021-05-11 07:24 UTC, johscheuer commented on config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
> +                  pattern: (\d+)\.(\d+)\.(\d+)
We may want to run/add some tests to ensure versions like `prerelease-5.6.2` and `test-1.2.3-test` etc. are actually working like expected.

2021-05-11 18:26 UTC, johscheuer approved these changes

2021-05-11 18:26 UTC, johscheuer commented on config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
> +                  pattern: (\d+)\.(\d+)\.(\d+)
That's fine to only test the `ParseFdbVersion` the Kubernetes validation should behave the same way.

2021-05-11 18:27 UTC, merged

2021-05-11 18:27 UTC, johscheuer commented
Thanks!