Add support for restoring specific key ranges.
FoundationDB/fdb-kubernetes-operator pull request #720
Opened 2021-05-27 18:43 UTC by brownleej

Resolves #691

2021-05-28 07:01 UTC, johscheuer requested changes

2021-05-28 14:40 UTC, brownleej commented on api/v1beta1/foundationdbrestore_types.go
> +// FoundationDBKeyRange describes a range of keys for a command.
In the future we are likely to use it for backup commands as well.

2021-05-28 17:24 UTC, brownleej commented on api/v1beta1/foundationdbrestore_types.go
> + * Copyright 2020-2021 Apple Inc. and the FoundationDB project authors
I've wondered this as well, and it may be worth talking about out-of-band.

2021-05-28 17:25 UTC, brownleej commented on controllers/suite_test.go
> -	cfg, err := testEnv.Start()
Yeah, I think that's the general expectation.

2021-05-28 17:27 UTC, brownleej commented on fdbclient/admin_client.go
> +		args = append(args, "-k", keyRangeString)
I think it's OK to defer that check to fdbrestore for now. As we get more experience with key-range restores we may be able to provide better visibility.

2021-06-02 06:37 UTC, johscheuer approved these changes
LGTM 👍

2021-06-02 06:38 UTC, johscheuer commented on api/v1beta1/foundationdbrestore_types.go
> +	// The key ranges to restore;.
```suggestion
	// The key ranges to restore.
```

NIT

2021-06-02 20:59 UTC, merged