Add initContainer securityContext to helm chart
FoundationDB/fdb-kubernetes-operator pull request #808
Opened 2021-07-02 03:51 UTC by funkypenguin

# Description

Hey guys! This PR simply uses the existing logic in the helm chart to insert a securityContext for each of the initContainers. We stumbled across this when trying to update to the latest chart version - our CI uses kube-score to lint our manifests, and wouldn't permit creating a pod without securityContext for its initContainers :)

## Type of change

*Please select one of the options below.*

- New feature (non-breaking change which adds functionality)

# Discussion

*Are there any design details that you would like to discuss further?*

# Testing

Successfully validate charts against kube-score, and deployed into multiple clusters without incident.

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

No

# Documentation

*Did you update relevant documentation within this repository?*

From what I can tell, the helm chart is not documented to the degree of detail which would require any changes resulting from this PR. If I'm wrong, I'm happy to update the docs if you point me to them.

# Follow-up

*Are there any follow-up issues that we should pursue in the future?* No

*Does this introduce new defaults that we should re-evaluate in the future?* No

2021-07-02 06:26 UTC, johscheuer requested changes
Only one small thing otherwise LGTM 👍

2021-07-02 06:26 UTC, johscheuer commented on helm/fdb-operator/values.yaml
> +  readOnlyRootFilesystem: true
Missing newline

2021-08-10 09:36 UTC, johscheuer reviewed
Friendly ping :)

2021-08-10 10:12 UTC, funkypenguin commented
Oops! Friendly pong :)

2021-08-11 06:48 UTC, johscheuer approved these changes
LGTM 👍

2021-08-11 06:48 UTC, merged