Enabling log file rotation
FoundationDB/fdb-kubernetes-operator pull request #831
Opened 2021-07-08 15:25 UTC by 09harsh

# Description
implemented log rotation as part of this PR. Is solved the issue #664

## Type of change

*Please select one of the options below.*

- Bug fix (non-breaking change which fixes an issue)
[x]New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation
- Other

# Discussion

*Are there any design details that you would like to discuss further?*
NO

# Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Manual testing?*

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

# Documentation

*Did you update relevant documentation within this repository?*

*If this change is adding new functionality, do we need to describe it in our user manual?*

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*

# Follow-up

*Are there any follow-up issues that we should pursue in the future?*

*Does this introduce new defaults that we should re-evaluate in the future?*

2021-07-08 15:57 UTC, johscheuer requested changes
One small thing

2021-07-08 15:57 UTC, johscheuer commented on setup/setup.go
> +			MaxSize:    operatorOpts.LogFileMaxAge,
```suggestion
			MaxSize:    operatorOpts.LogFileMaxSize,
```

2021-07-08 17:25 UTC, johscheuer reviewed
One thing otherwise LGTM 👍 Did you tested the changes locally?

2021-07-08 17:25 UTC, johscheuer commented on setup/setup.go
> +	fs.BoolVar(&o.CompressOldFiles, "compress", false, "It determines if the rotated log files should be compressed using gzip or not.")
```suggestion
	fs.BoolVar(&o.CompressOldFiles, "compress", false, "Defines if the rotated log files should be compressed using gzip or not.")
```

Just for consistency

2021-07-13 17:07 UTC, 09harsh commented on setup/setup.go
> +	fs.BoolVar(&o.CompressOldFiles, "compress", false, "It determines if the rotated log files should be compressed using gzip or not.")
Yes I tested the changes locally

2021-07-13 19:13 UTC, johscheuer approved these changes
LGTM 👍

2021-07-13 19:13 UTC, merged