Only replace on changed node selector if pod spec hash has changed
FoundationDB/fdb-kubernetes-operator pull request #973
Opened 2021-11-05 16:15 UTC by benzim

# Description

This is a fix for https://github.com/FoundationDB/fdb-kubernetes-operator/issues/950.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Discussion

This will trigger a replacement if any part of the pod template spec is changed if there is a [PodNodeSelector](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector). Which isn't ideal but is better than the previous behavior of the pods being replaced endlessly.

# Testing

I ran unit tests and manually deployed the operator and cluster in a namespace with a PodNodeSelector.

2021-11-08 08:11 UTC, johscheuer requested changes

2021-11-08 08:11 UTC, johscheuer commented on internal/replacements/replacements.go
> +	if cluster.Spec.UpdatePodsByReplacement || !equality.Semantic.DeepEqual(pod.Spec.NodeSelector, expectedNodeSelector) {
Can we still leave the node selector check in a different if statement? That makes it easier to see why the Pod was replaced with this change we will only see "specHash has changed from ... to ..." but we can be more precise by logging that the node selector doesn't match.

2021-11-10 07:38 UTC, johscheuer reviewed
The changes look good to me, could you add an additional test case here: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/internal/replacements/replacements_test.go#L238-L255 where we change the nodeSelector of the Pod. That shouldn't result in a replacement with the new changes.

2021-11-10 17:58 UTC, benzim commented
@johscheuer Hopefully this isn't out of scope for this PR, but the replacements tests weren't running when I ran `make test` so I added some stuff to get the replacements tests running and passing.

2021-11-10 18:30 UTC, johscheuer approved these changes
LGTM 👍 Thanks for fixing the test suite.

2021-11-10 19:08 UTC, merged